### ISSUE TITLE
Issue: Cannot read property 'length' of undefined when globalize is used

### ISSUE THREAD

**Issue by MounikaMuthyala** [DevExpress/devextreme-examples#23]
I run into the following error when npm start is executed following npm install. Please guide me on what am I doing wrong. I use angular2

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\...\node_modules\types
cript\lib\typescript.js:8980:109)

 at parseSourceFileWorker (C:\...\node_modules\typescript\lib\typescript.js:8940:26)
    at Object.parseSourceFile (C:\...\node_modules\typescript\lib\typescript.js:8899:26)
    at Object.createSourceFile (C:\...\node_modules\typescript\lib\typescript.js:8727:29)
    at WebpackCompilerHost.getSourceFile (C:\...\node_modules\@ngtools\webpack\src\compiler_host.js:2
10:27)

**Comment by nightskylark** [comment]
Hello,
The issue does not reproduce now.
In case you still have an issue, please, [create a ticket](https://www.devexpress.com/Support/Center/Question/Create) in our Support Center. Our support engineers are always ready to help with any DevExpress product.
